[workspace]

members = [
    "cpu_kernel_raytracer",
    "cuda_kernel_raytracer",
    "math",
    "raytracer",
    "raytracer_example",
    "raytracer_lib_no_std",
    "raytracer_lib_std",
     "raytracer_challenge_reference_impl",
     "create_street",
     "game-physics"
]
