[workspace]

members = [
    "raytracer_challenge_reference_impl",
    "playground/threadpool_fractal",
    "curves",
    "webgui/backend",
    "micrograd-rs",
    "render_benny",
    "playground/test-serde-perf"
]